### ISSUE TITLE
Use Tasklists?

### ISSUE THREAD

**Issue by berylliumquestion** [LazyDuchess/OpenTS2#13]
So a neat little feature with github I found is that you can put a little tasklist with all of your issues

--

For example
## Todo
- [ ] Make minimum playable program
- [ ] Finish data parsing methods
- [ ] Make mod api
- [ ] #2 
- [ ] #7 

etc. etc.
Just do it like this `- [ ] Some sort of task or - [ ] #2`
You can see more with this video! :D https://www.youtube.com/watch?v=BplF7vHXewA
